import tkinter as tk
tab=tk.Tk()
tab.title("simple calculator")
tab.geometry("400x400")
a=tk.IntVar()
b=tk.IntVar()
c=tk.IntVar()
l1=tk.Label(tab,text="Enter A Value",font=("calibri",10,"bold"),fg="violet")
l1.place(x=50,y=50)
e1=tk.Entry(tab,textvariable=a)
e1.place(x=180,y=50)
l2=tk.Label(tab,text="Enter B Value",font=("calibri",10,"bold"),fg="violet")
l2.place(x=50,y=100)
e2=tk.Entry(tab,textvariable=b)
e2.place(x=180,y=100)
l3=tk.Label(tab,text="result",font=("calibri",10,"bold"),fg="violet")
l3.place(x=50,y=150)
e3=tk.Entry(tab,textvariable=c)
e3.place(x=180,y=150)
def add():
    x=a.get()
    y=b.get()
    c.set(x+y)
def sub():
    x=a.get()
    y=b.get()
    c.set(x-y)
def multiply():
    x=a.get()
    y=b.get()
    c.set(x*y)
def division():
    x=a.get()
    y=b.get()
    c.set(x/y)
def cancel():
    a.set(" ")
    b.set(' ')
    c.set(' ')
b1=tk.Button(tab,text="Add",bg="green",command=add)
b1.place(x=90,y=200)
b3=tk.Button(tab,text="sub",bg="green",command=sub)
b3.place(x=130,y=200)
b4=tk.Button(tab,text="multiply",bg="green",command=multiply)
b4.place(x=170,y=200)
b5=tk.Button(tab,text="Division",bg="green",command=division)
b5.place(x=230,y=200)
b2=tk.Button(tab,text="Cancel",bg="red",command=cancel)
b2.place(x=290,y=200)
tk.mainloop()